// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using BaseNorthWindCoreLibrary.Classes.North.Classes;

#nullable disable

namespace NorthWindCoreLibrary.Models
{
    public partial class Customers
    {
        public Customers()
        {
            Orders = new HashSet<Orders>();
        }

        /// <summary>
        /// Id
        /// </summary>
        public int CustomerIdentifier { get; set; }
        /// <summary>
        /// Company
        /// </summary>
        public string CompanyName { get; set; }
        /// <summary>
        /// ContactId
        /// </summary>
        public int? ContactId { get; set; }
        /// <summary>
        /// Street
        /// </summary>
        public string Street { get; set; }
        /// <summary>
        /// City
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// Region
        /// </summary>
        public string Region { get; set; }
        /// <summary>
        /// Postal Code
        /// </summary>
        public string PostalCode { get; set; }
        /// <summary>
        /// CountryIdentifier
        /// </summary>
        public int? CountryIdentifier { get; set; }
        /// <summary>
        /// Phone
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// Fax
        /// </summary>
        public string Fax { get; set; }
        /// <summary>
        /// ContactTypeIdentifier
        /// </summary>
        public int? ContactTypeIdentifier { get; set; }
        /// <summary>
        /// Modified Date
        /// </summary>
        public DateTime? ModifiedDate { get; set; }

        public virtual Contacts Contact { get; set; }
        public virtual ContactType ContactTypeIdentifierNavigation { get; set; }
        public virtual Countries CountryIdentifierNavigation { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public override string ToString()
        {
            return $"{CustomerIdentifier} - {CompanyName}";
        }

        public static Expression<Func<Customers, CustomerEntity>> Projection
        {

            get
            {
                return (customer) => new CustomerEntity()
                {
                    CustomerIdentifier = customer.CustomerIdentifier,
                    CompanyName = customer.CompanyName,
                    Street = customer.Street,
                    City = customer.City,
                    PostalCode = customer.PostalCode,
                    ContactTypeIdentifier = customer.ContactTypeIdentifier.Value,
                    ContactTitle = customer.ContactTypeIdentifierNavigation.ContactTitle,
                    ContactId = customer.ContactId,
                    CountryName = customer.CountryIdentifierNavigation.Name,
                    FirstName = customer.Contact.FirstName,
                    LastName = customer.Contact.LastName,
                    ContactIdentifier = Convert.ToInt32(customer.ContactId),
                    Contacts = customer.Contact,
                    CountryIdentifier = customer.CountryIdentifier,
                    CountryNavigation = customer.CountryIdentifierNavigation,
                    LastUpdated = customer.ModifiedDate
                };
            }

        }
    }
}